### ISSUE TITLE
Use Infini-gram to retrieve term frequencies for the Wordnet and OBO Foundry ontologies

### ISSUE THREAD

**Issue by g-simmons** [g-simmons/persona-research-internship#144]
## Background
*relevant information and motivation for this task*
The infinigram paper claims to provide an efficient method for computing pretraining term frequencies.

https://arxiv.org/pdf/2401.17377

We need to get pretraining frequencies for:
- [ ] WordNet
- [ ] OBO Foundry ontologies

## Task
*high-level task description*

## How To
*specific guidance on implementation*
- [ ] Obtain term lists for the Wordnet and OBO Foundry ontologies
  - Contact @ranr9131 for details
- [ ] For each term in each term list, obtain its frequency in the Pile dataset, using the Infinigram API. Save the code that you used as a file in this repository.
- [ ] If the Infinigram API cannot be used, write a few sentences here describing why that's the case.

## Undecided
*implementation details that haven't been decided yet ("known-unknown" status)*
I have not investigated the infinigram API deeply. There is a chance it could be unavailable, or that it doesn't do what I think it does based on skimming the paper. That's fine if that's the case, please report it here.

## Expected Results
*what results are expected from completing this issue*
### Code
Code that calls the Infinigram API to retreive term frequencies, as a Python script in this repository.
### Data
Data files, (jsonl format preferred) that store the pretraining term frequencies for each ontology, added to this repository.
### Writing
In the case that infinigram cannot be used, a few sentences as a reply stating why.

**Comment by g-simmons** [comment]
@lsomoza6464 note from meeting today:

Add a command-line interface that accepts (at least) two parameters:
- the index (a path to the infinigram index file)
- the ontology (a path to the term list txt file)
