### ISSUE TITLE
Task: Include llm_persona_website in this repo

### ISSUE THREAD

**Issue by g-simmons** [g-simmons/persona-research-internship#171]
## Background
*relevant information and motivation for this task*
I've moved the `g-simmons/llm_persona_website` repo to a subfolder of `g-simmons/persona-research-internship`.

The new site deploys to https://g-simmons.github.io/persona-research-internship/. We would like for any links we sent (for example on Discord) to still work, so we should configure the old site to redirect to the new one. I added a redirect in index.html in the old site already.

## Task
*high-level task description*
Complete migration of `g-simmons/llm_persona_website` to `g-simmons/persona-research-internship`.

## How To
*specific guidance on implementation*

There are some steps left to complete the migration:

- [x] Invite Joe to this repo.

In the old repo:
- [ ] Check if other pages besides the homepage redirect correctly. If not, add redirects on the subpages.
- [ ] Change the settings on the old repo to block push access.
- [ ] Update the README on the old repo to indicate that the site has been moved.
- [ ] Move open issues from the old repo to the `g-simmons/persona-research-internship` repo.

## Undecided
*implementation details that haven't been decided yet ("known-unknown" status)*

## Expected Results
*what results are expected from completing this issue*
### Code
Code changes in the old site, as described in How To section above.
