### ISSUE TITLE
Task: Add capabilities to study the OLMo and OLMo 2 series of models

### ISSUE THREAD

**Issue by g-simmons** [g-simmons/persona-research-internship#212]
## Background
*relevant information and motivation for this task*
Read about the OLMo 2 model series [here](https://allenai.org/olmo).

## Task
*high-level task description*
Check whether the OLMo 2 model series can be used in our experimental setup.
- [ ] OLMo
- [ ] OLMo2

## How To
*specific guidance on implementation*
Read (skim) the OLMo 2 blog post, paper, etc. to answer the following:
- [ ] Are the OLMo 2 models available for research use? How can we download the models? Are they on Huggingface?
- [ ] Does the OLMo 2 model series have multiple checkpoints at varying training steps?
- [ ] What model sizes are available? Model size is expressed in number of parameters, like "70M" or "8B".
- [ ] Do we need to modify our code to access the OLMo 2 model unembedding matrices?

Best case scenario: we just need to change a top-level parameter from "pythia" to "olmo" and all the other code just works.

## Undecided
*implementation details that haven't been decided yet ("known-unknown" status)*

## Expected Results
*what results are expected from completing this issue*
### Writing
Answers to the above questions. In general, report on whether we can use the OLMo 2 models or not.

**Comment by g-simmons** [comment]
Raymond's notes from dec 7 meeting:

Olmo 
1B and 7B
Training checkpoints available every 1k steps, not sure what the maximum step was

Olmo 2
model sizes 7B and 13B
I think we remember seeing multiple training checkpoints for olmo 2 also

**Comment by g-simmons** [comment]
The different steps are available in different branches in huggingface:

e.g. https://huggingface.co/allenai/OLMo-2-1124-7B/tree/main

<img width="533" alt="image" src="https://github.com/user-attachments/assets/0df59b5a-dbf5-4d12-911b-7399387c2e98">

**Comment by g-simmons** [comment]
It looks like the models are available at a variety of post-training checkpoints:

DPO = Direct Preference Optimization
SFT = Supervised Fine-tuning

I am not familiar with RLVP but it sounds like something similar to RLHF.

<img width="686" alt="image" src="https://github.com/user-attachments/assets/46597f7f-3ba0-471b-a943-fb832029a6ab">

**Comment by g-simmons** [comment]
We should find out (@ranr9131 ) whether the post-training were applied sequentially. 

If so, we can extend the plots for ontology score vs. performance by adding the SFT and DPO steps at the end of the plot.
